deps: bump io.quarkus:quarkus-bom from 3.16.3 to 3.17.2 (#648)
Bumps [io.quarkus:quarkus-bom](https://github.com/quarkusio/quarkus)
from 3.16.3 to 3.17.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.17.2</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/7462">#7462</a>
- Hibernate fails on complex orphanDelete=true cases and bump version
upon merge calls involving entities without change</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/35980">#35980</a>
- Health UI access wrong health endpoint with management interface</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/43056">#43056</a>
- Double Array Hibernate <code>@JdbcTypeCode</code>(SqlTypes.ARRAY)
causes NullPointerException with 6.6.0.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/43296">#43296</a>
- AssertionError in EntityInitializerImpl.resolveInstanceSubInitializers
after upgrading to 3.14</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/43845">#43845</a>
- Exemplars are not recorded for metric
<code>http_server_requests*</code></li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44016">#44016</a>
- Micrometer exemplars on HTTP</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44117">#44117</a>
- TestProfile's getEnabledAlternatives CDI BEAN leaks to unrelated
TestProfile's test</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44261">#44261</a>
- Improve Qute documentation</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44391">#44391</a>
- Upgrade to Hibernate ORM 6.6.3.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44454">#44454</a>
- Hibernate FetchNotFoundException</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44511">#44511</a>
- NPE during custom bean invocation via PreAuthorize annotation in
Quarkus RESTEasy</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44543">#44543</a>
- Fix buildpack docker host handling for macos</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44564">#44564</a>
- A NoSuchMethodException is raised when a rest resource is called with
a Jakarta Reader/Writer interceptor defined</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44568">#44568</a>
- <code>@AuthorizationPolicy</code> is not compatoble with kotlin
suspend functions</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44576">#44576</a>
- Cannot build TODO demo app on windows into uber-jar since quarkus
3.16.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44584">#44584</a>
- Fix wrong web endpoint path for resource on Windows</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44586">#44586</a>
- Bump smallrye-fault-tolerance.version from 6.6.2 to 6.6.3</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44589">#44589</a>
- Copyedits for style, security-jwt.adoc</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44592">#44592</a>
- Docs: dev mode differences - remove the link for old Dev UI</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44594">#44594</a>
- Google Cloud Function gen 2 is now the default</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44599">#44599</a>
- Build fails with &quot;Method too large&quot; exception</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44602">#44602</a>
- Qute docs improvement</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44603">#44603</a>
- Copyedits for style, security-jwt-build.adoc</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44608">#44608</a>
- Bump testcontainers.version from 1.20.3 to 1.20.4</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44610">#44610</a>
- Qute: Unexpected primitive equality</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44613">#44613</a>
- Register method for reflection when read or write interceptors
exist</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44615">#44615</a>
- Qute: if section - adjust the evaluation rules for equality
operators</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44638">#44638</a>
- Clean up effects of test profiles when <code>@QuarkusMainTest</code>
completes</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44641">#44641</a>
- NoClassDefFoundError in ShutdownTask when running
BuildMetricsTest</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44646">#44646</a>
- Failing to apply <code>@SecureField</code> to a generic with nested
objects.</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44647">#44647</a>
- Do not add host:port to Health path in Health UI</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44649">#44649</a>
- Register <code>jakarta.json.spi.JsonProvider</code> service
provider</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44667">#44667</a>
- Pass secured method arguments into security checks for
<code>@PreAuthorize</code> security annotation on SpringWeb
endpoints</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44668">#44668</a>
- Support <code>@AuthorizationPolicy</code> on suspended Kotlin endpoint
methods</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44669">#44669</a>
- Quarkus REST Jackson: Improve detection of generic fields annotated
with the <code>@SecureField</code> and allow to explicitly enable secure
serialization</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/44674">#44674</a>
- Qute: Rendering Timeout Instead of Throwing TemplateException for
Missing Keys in {#let} and {#set} Constructs</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44677">#44677</a>
- Properly reset Quarkus populated Jackson ObjectMapper</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44678">#44678</a>
- Fix glob to regex convertion to properly handle **/*.suffix</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44679">#44679</a>
- Config Doc - Improve HTML Javadoc -&gt; Asciidoc conversion</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44682">#44682</a>
- Qute: fix handling of missing properties in strict mode</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44684">#44684</a>
- Remove line</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44685">#44685</a>
- Add documentation for <code>@WithTestResource</code> to getting
started testing</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44698">#44698</a>
- Bump hibernate-search.version from 7.2.1.Final to 7.2.2.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44704">#44704</a>
- Fix TLS config Javadoc typo</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44709">#44709</a>
- Fix leftover -reactive properties references in REST client guide</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/44754">#44754</a>
- Fix retry count in remote dev mode error message</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/3307effe7fb744b4f149c48babc3f0c83c0c07fb"><code>3307eff</code></a>
[RELEASE] - Bump version to 3.17.2</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/2b6d8a60fb2ef601f9bae84e475fc40604848f60"><code>2b6d8a6</code></a>
Revert &quot;Split creation of the Set to match unknown properties to
avoid Method...</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/18b863ca67e311527588e3094fbfee5ac296355d"><code>18b863c</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/44782">#44782</a>
from gsmet/3.17.1-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/1261e269267545bdac67932782cf60ed00cfa51a"><code>1261e26</code></a>
Bump org.jboss.logmanager:jboss-logmanager</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/0de52088409474444345b8bd473abf6f98d26ae3"><code>0de5208</code></a>
Fix retry count in remote dev mode error message</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/26126633501b0bc3f62436c891ce96a640a01b38"><code>2612663</code></a>
Address leftovers in testing docs from <a
href="https://redirect.github.com/quarkusio/quarkus/issues/44685">#44685</a></li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/8d6844e0528e8e4011a7cef578fc4247b6b21216"><code>8d6844e</code></a>
Add documentation for <a
href="https://github.com/WithTestResource"><code>@​WithTestResource</code></a>
to getting started testing</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/1099725be665e1322c3f6b42d94d43f4578abf4f"><code>1099725</code></a>
Temporarily disable OIDC wiremock tests using expired certificates</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/6c57eb6715a2a5597714c0b737788b796c161035"><code>6c57eb6</code></a>
Do not add host:port to Health path in Health UI</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/1b2e4318a955bb2c82ccc3959610f1051582dc0b"><code>1b2e431</code></a>
Register jakarta.json.spi.JsonProvider service provider</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.16.3...3.17.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=io.quarkus:quarkus-bom&package-manager=gradle&previous-version=3.16.3&new-version=3.17.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Lukáš Petrovický <lukas@petrovicky.net>